### ISSUE TITLE
Errors when loading the component

### ISSUE THREAD

**Issue by briis** [briis/smartweather#2]
Users get several errors when setting up the component. It is still unclear where the error occurs, but some of the errors that are logged are:

`Invalid config for [smartweather]: required key not provided @ data['platform']. Got None. (See ?, line ?). Please check the docs at https://home-assistant.io/components/smartweather/` 

and

`Invalid config for [smartweather]: expected a dictionary for dictionary value @ data['smartweather']. Got [OrderedDict([('station_id', '1234'), ('api_key', '20c70eae-e62f-4d3b-b3a4-8586e90f3ac8')])]. (See ?, line ?). Please check the docs at https://home-assistant.io/components/smartweather/`

**Comment by lubbertkramer** [comment]
I have added the files and i’'m trying to only add the smartweather to connect my weatherflow. I have downloaded your git and renamed the folder to smartweather

![image](https://user-images.githubusercontent.com/8224586/54440394-e0668080-473a-11e9-99f4-e406cddbbcfd.png)

![image](https://user-images.githubusercontent.com/8224586/54440452-0429c680-473b-11e9-9db4-081e7baf4eb9.png)

I'm running HA 0.89.2 in docker on a Ubuntu NUC

![image](https://user-images.githubusercontent.com/8224586/54440483-1572d300-473b-11e9-8a48-742606e673ef.png)

**Comment by briis** [comment]
Bug fixed and closed in release V0.0.4
