### ISSUE TITLE
Deprecation warning from component on 0.110.0

### ISSUE THREAD

**Issue by mdegat01** [briis/smartweather#32]
I ran check config before upgrading to 0.110 and received these warnings from its output:
```
WARNING:homeassistant.components.binary_sensor:BinarySensorDevice is deprecated, modify SmartWeatherBinarySensor to extend BinarySensorEntity
```
Since this is only a warning I assume the integration still works for now (haven't actually upgraded yet, working out other issues first).  But wanted to get an issue down to let you know.

Ludeeus has been linking to [this blog post](https://developers.home-assistant.io/blog/2020/05/14/entity-class-names/) to explain what's going on when people comment that they see this warning in their logs on 0.110.  Seems like just a name change for some base classes.

**Comment by briis** [comment]
Yes, it is just a warning, and the component will still work. They change the naming from BinarySensorDevice to BinaryEntity, but there is a failover for now. It is easily fixed, and I will do that within the next few days. But you can still upgrade, you will just get this warning when HA starts.

**Comment by briis** [comment]
V1.0.5 is released, which removes this warning.
