### ISSUE TITLE
Tempest UDP - Lightning strike event

### ISSUE THREAD

**Issue by GH2user** [briis/smartweather#38]
Hi,

Hoping to receive a Tempest really soon now and checking the possibilities with Home Assistant your repositories came up first.

Looking at the UDP-API v143 it seems the Lightning Strike Event also has an Energy component which is not used in your various weatherflow projects.
[https://weatherflow.github.io/SmartWeather/api/udp/v143/](url)

Can you add this to the UDP listeners?

**Comment by briis** [comment]
Hi,
This is actually the wrong place to ask for this, as this component is the REST version and not the UDP version. The right place to raise this issue [is here](https://github.com/briis/smartweatherudp).
However I left continued development of the UDP component to other people, as I am no longer using it.

With that said, you are right that there is an Energy component in the `evt_strike` group, but this particular group is not being pulled. The lightning data comes from either `obs_air` if you have an AIR unit or from `obs_st` if you have a Tempest unit. And in both of these the Energy value is not supplied. The reason I guess, is that Weatherflow does not really now what that value actually represents, and as you can see it also does not have any Unit type attached to it.

But try and add an Issue in the other Project and see if it can be done for you. I will close this issue now.
