### ISSUE TITLE
2.0.6 Upgrade and Custom Weather Card

### ISSUE THREAD

**Issue by lazerdave** [briis/smartweather#41]
Even with this in my configuration.yaml
```
weather:
  - platform: smartweather
    api_key: <My Dark Sky API key>
```

my weather cards have broken in this upgrade.

```
current: true
details: true
entity: weather.smartweather
forecast: true
hourly_forecast: true
number_of_forecasts: '4'
type: 'custom:weather-card'
```

Any tips?

**Comment by trancen** [comment]
I'm having the same issue where the card is broken, don't see anything in the logs

**Comment by briis** [comment]
Hi both,
I am a little confused. The title of this issues indicate an issue with V2.0.6, but this integration is at 2.0.3 - is that just a typo?
Anyway as [stated in the README](https://github.com/briis/smartweather#upgrade-from-version-1x) you have to remove ALL references for `smartweather` from your YAML files before you upgrade, as yaml configuration is no longer supported.

I also assume that the Lovelace Weather Card you are using is this: https://github.com/bramkragten/weather-card. As also stated in the Upgrade notes, the entity names will changes, so your `entity: weather.smartweather` would have gotten a new name, with your location attached. Please check the developer tools to find the right entity.

Please let me know if any of this helps?

**Comment by lazerdave** [comment]
Looks like I had a stray entry in there I hadn't caught.

Thanks!

**Comment by trancen** [comment]
Mine too as well, resolved for me. Thanks

**Comment by briis** [comment]
Great you both got it fixed. I will close this issue now.
