### ISSUE TITLE
Descriptive summary sensors

### ISSUE THREAD

**Issue by mdegat01** [briis/smartweather#43]
Love this integration, excellent work. Was really happy to see you re-worked it to eliminate the dependency on dark sky now that Apple is cutting off their API. 

You've almost covered everything I used to use the dark sky integration for except for one thing. The dark sky integration provided these useful summary sensors that provide a human-readable description of what is coming up in the next week, day and hour. For instance, right now I have these three with the following values:

- `sensor.dark_sky_minutely_summary` - `Clear for the hour.`
- `sensor.dark_sky_hourly_summary` - `Mostly cloudy throughout the day.`
- `sensor.dark_sky_daily_summary` - `Rain on Monday through Friday.`

I really like these sensors for notifications, especially the minutely one. When a weather event is happening that I want to be notified about I use the value of the minutely sensor as the notification message since it gives me a nice overview of what is going on (along with whatever data caused the scenario I wanted to be notified about). 

Would it be possible for this integration to create similar sensors? Not a huge deal but I would really appreciate it. Then I could uninstall the dark sky integration and forget about it.

**Comment by briis** [comment]
Thanks.
I am not sure Weatherflow provides that kind of information. But I'll look through the current API and see what is possible.

**Comment by briis** [comment]
Unfortunately the only text that is available, is the Condition text, like *Clear*, *Rainy* etc. These are already in the sensors and can be extracted from there. For your specific use case, you would then need to run the Forecast mode as *hourly*.
I know this is not what you wanted, but the data is not there - at least not for now.

I will close this issue.

**Comment by mdegat01** [comment]
No worries, figured that might happen. Thanks for checking for me!
