### ISSUE TITLE
Forecast -> precipitation should be null instead of 0 when there's none

### ISSUE THREAD

**Issue by scstraus** [briis/smartweather#45]
All the other weather platforms send null instead of 0 when there's no precipitation. Sending a 0 causes some problems with some cards like the custom weather card chart card. Any chance you could change it to null like the other weather platforms?

**Comment by briis** [comment]
Sure thing. I wasn't even aware of that. But just checked a few Weather Integrations and you are right.
I'll make the change.

**Comment by briis** [comment]
V2.0.5 released. Please close this issue if it now delivers the expected data..

**Comment by scstraus** [comment]
Wow, kickass! That was fast! Seems to have worked. Testing a bit more with the weather card now. Thanks!
