### ISSUE TITLE
Weather State

### ISSUE THREAD

**Issue by captainlegacy** [briis/smartweather#47]
Since upgrading to 2.0.5 the state of the weather entity is displaying "pouring" when it is raining at all or rain is likely per the Tempest app

**Comment by briis** [comment]
The condition and icons should map to the 'official' way WeatherFlow has defined it.
When the weather entity is displaying "pouring", could you go in to the Developer Tools, and search for the weather entity. Here you will find an attribute called `current_icon` and then tell me what the value is. 
I need to check if I messed up the mapping.

**Comment by captainlegacy** [comment]
Here is what it is showing for me, let me know if there is anything else you need. Thanks!

temperature: 46.22
humidity: 93
pressure: 30.43
wind_bearing: 334
wind_speed: 2
attribution: Powered by a WeatherFlow Smart Weather Station
forecast: 
- datetime: '2020-12-16T06:00:00+00:00'
  temperature: 46.4
  precipitation: 0
  precipitation_probability: 80
  condition: pouring
  wind_speed: 11.2
  wind_bearing: 188
  icon: rainy
- datetime: '2020-12-16T07:00:00+00:00'
  temperature: 46.4
  precipitation: 0
  precipitation_probability: 50
  condition: pouring
  wind_speed: 11.2
  wind_bearing: 186
  icon: rainy
- datetime: '2020-12-16T08:00:00+00:00'
  temperature: 46.4
  precipitation: 0
  precipitation_probability: 40
  condition: rainy
  wind_speed: 11.2
  wind_bearing: 184
  icon: possibly-rainy-night
- datetime: '2020-12-16T09:00:00+00:00'
  temperature: 46.4
  precipitation: 0
  precipitation_probability: 35
  condition: rainy
  wind_speed: 9
  wind_bearing: 179
  icon: possibly-rainy-night
- datetime: '2020-12-16T10:00:00+00:00'
  temperature: 46.4
  precipitation: null
  precipitation_probability: 20
  condition: rainy
  wind_speed: 9
  wind_bearing: 173
  icon: possibly-rainy-night
- datetime: '2020-12-16T11:00:00+00:00'
  temperature: 46.4
  precipitation: null
  precipitation_probability: 10
  condition: cloudy
  wind_speed: 9
  wind_bearing: 170
  icon: cloudy
- datetime: '2020-12-16T12:00:00+00:00'
  temperature: 46.4
  precipitation: null
  precipitation_probability: 25
  condition: rainy
  wind_speed: 6.7
  wind_bearing: 166
  icon: possibly-rainy-night

**Comment by briis** [comment]
Found the error - rainy was mapping to both rainy and pouring. Need to figure out what is send from the API when it is pouring.
I'll release something as soon as it is fixed.

**Comment by briis** [comment]
Basically "pouring" does not exist in WeatherFlow terms. We have 3 possible conditions:
* rainy
* possibly-rainy-day
* possibly-rainy-night

In HA there is only rainy and pouring, so I will remove pouring from the mapping. Do you agree with this solution?

**Comment by captainlegacy** [comment]
Yes that makes sense. I guess I'm not sure why it is saying its "pouring" if it is not currently raining. It seems like it chooses "rainy" if the precipitation probability is >=50 based off the first few entries?

**Comment by briis** [comment]
The value that comes from the API is out of my control - Weatherflow says they are AI based, so hopefully they will get better over time. 
Btw, the Forecast API is still not officially released, so some changes might occur when that happens.

I'll make the changes, and send a new release. (Have a few other things I am working on with this, so it might take a few days)

**Comment by captainlegacy** [comment]
No worries, just thought I'd point it out. Thanks!

**Comment by briis** [comment]
Closed with the release of V2.1. Let me know if you still see the problem
