### ISSUE TITLE
Tempest - two incorrect values

### ISSUE THREAD

**Issue by Notrial** [briis/smartweather#48]
Hi and great job with this integration. I noticed two incorrect values on my Tempest. Rest seem to be working just fine.

1. Wind gust speed equals Wind Speed
2. Rain today always shows 0

Hopefully this can be fixed. Let me know what I can do on my end.

**Comment by briis** [comment]
Are you talking about the Sensor or the Weather entity?
Rain today equals `precip_accum_local_day` from the REST API, and Wind Gust equals `wind_gust`. So these should be the correct values.
What is the Tempest App saying?

**Comment by Notrial** [comment]
Sorry, I guess I probably posted in the wrong spot. I was using your UDP component till yesterday. There I had those 2 issues with sensors. Your "WeatherFlow Smart Weather" integration works much better (and no issues with readings). I suppose your UDP one was older implementation? Although I suppose it was better in a way that it reads the data locally. If WeatherFlow cloud goes down, so does our readings :(

**Comment by briis** [comment]
No problem - you got me confused 
I made the UDP version a while ago, but as I did not have access to the HW for a while, I abandoned development. Mark Turner (@LuckyJayDIY) is making necessary adjustments now, so it is not dead.

You are right, local is always better, and when Tempest units are available in Europe, I will most likely get one, and then I can do some development on that again.
