### ISSUE TITLE
Entities disappeared after update to latest version

### ISSUE THREAD

**Issue by dennyChandler** [briis/smartweather#50]
Hey all! Love the integration, just updated today and saw my entities all disappear, I still have the Device, but no entites. Logs below:

`2021-01-08 13:56:41 ERROR (MainThread) [custom_components.smartweather] Unexpected error fetching smartweather data: 'air_temp_high_color'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 132, in _async_update_data
return await self.update_method()
File "/usr/local/lib/python3.8/site-packages/pysmartweatherio/client.py", line 99, in get_daily_forecast
return await self._forecast_data(FORECAST_TYPE_DAILY, 0)
File "/usr/local/lib/python3.8/site-packages/pysmartweatherio/client.py", line 296, in _forecast_data
"air_temp_high_color": row["air_temp_high_color"],
KeyError: 'air_temp_high_color'`

Installed using HACS, was running up until update today. HASS OS info below:

`

Version | 2021.1.0
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.4.79-v8
CPU Architecture | aarch64
Timezone | America/Chicago

HACS
GitHub API | ok
-- | --
Github API Calls Remaining | 4712
Installed Version | 1.9.0
Stage | running
Available Repositories | 709
Installed Repositories | 11
`

please let me know if I need to provide more information.

Thanks!

**Comment by briis** [comment]
The Forecast API at WeatherFlow has changed, removing some values like air_temp_high_color. Will look in to it ASAP and post a fix

**Comment by dennyChandler** [comment]
Thank you for the quick response! I appreciate it @briis I'll test it as soon as it is released! I freakin love integrating this into my home.

**Comment by cxdn** [comment]
Glad to hear it is being fixed. I just got it setup last night and was disappointed to see only to the device but no entities. I'm relatively new to HA so it's good to know it's not just me.

**Comment by briis** [comment]
New release is out now, which fixes this. Please close the issue, if it works for you.

**Comment by dennyChandler** [comment]
An uninstall of integration -> update of hacs integration -> restart -> re-addition of integration in HASS worked like a charm! Thank you!

**Comment by cxdn** [comment]
> An uninstall of integration -> update of hacs integration -> restart -> re-addition of integration in HASS worked like a charm! Thank you!

Unfortunately this did not work for me and I am still having the described issue. I removed the integration, deleted from hacs, removed hacs entirely. Reinstalled hacs, reinstalled weatherflow repo, reintegrated in HA and still only see 1 device and no entities. .

**Comment by briis** [comment]
Anything in the Home Assistant Log files you could post?

**Comment by cxdn** [comment]
A spun up a clean HA VM just see if I could get it working. All it has on it is 'Terminal & SSH', HACS, and your Weatherflow integration. I still just get 1 device (my weather station) and no entities. All that is in the logs:

```
2021-01-11 16:47:13 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-11 21:16:11 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```

I guess I will try either manual install of HACS or manual install of this custom integration or both. Sorry I don't have more information to provide.

**Comment by briis** [comment]
Could you provide me with your Station ID, then I can try it from my end, and see if I get some errors we can work with.
Also are you using your own Authentication Token, or the public developer Token? (Which has been withdrawn, but might still work)

**Comment by cxdn** [comment]
Station ID is 24530. Using my own Api token, which I've regenerated each
time trying troubleshooting.

Truly appreciate the help

**Comment by briis** [comment]
It seems there is problems with your data upload to WeatherFlow. If you [go here](https://weatherflow.github.io/Tempest/api/swagger/#!/observations/getStationObservation), Authorize with your key, then this is what you get. Here you should get your data, but instead I see this line: `SUCCESS - Either no capabilities or no recent observations`, meaning that your station exist, but no data is recorded.

Are you sure your Hub is connected to WiFi, and is sending data?

```json
{
  "station_id": 24530,
  "station_name": "Edgewood Farm Rd",
  "public_name": "Edgewood Farm Rd",
  "latitude": 39.45219,
  "longitude": -77.42475,
  "timezone": "America/New_York",
  "elevation": 118.0006484985352,
  "is_public": true,
  "status": {
    "status_code": 0,
    "status_message": "SUCCESS - Either no capabilities or no recent observations"
  },
  "station_units": {
    "units_temp": "f",
    "units_wind": "mph",
    "units_precip": "in",
    "units_pressure": "mb",
    "units_distance": "mi",
    "units_direction": "cardinal",
    "units_other": "imperial"
  },
  "outdoor_keys": [],
  "indoor_keys": [],
  "obs": []
}
```

**Comment by cxdn** [comment]
Thanks for this info. I believe it is, I get updates and observations to my
devices. However I have had issues with the hub in the past. I now suspect
it is an issue between the hub and my home network.

I'll dig into this further and let you know if I get it working.

Thanks,

**Comment by cxdn** [comment]
Thanks for your help. It is now working just as expected. Not sure the
exact issue but resetting the hub and station and a fresh setup took care
of it.

**Comment by briis** [comment]
Fantastic. Have a great day.
