### ISSUE TITLE
Pressure readings bug

### ISSUE THREAD

**Issue by Notrial** [briis/smartweather#52]
Hey m8, It's Tempest guy again :)

I think I discovered a bug of some sort. I'm checking my pressure readings (both Sea level and station) and I notice it drops to 0 a few times a day, which naturally messes up with the graphs, ranges etc.

Please take a look at the screenshot below:
![image](https://user-images.githubusercontent.com/36201754/104169683-3b816100-5400-11eb-8f78-56b3dd79dba1.png)

I don't see those "0" values in Weatherflow app / cloud, so it must be some sensor or API issue. Any clues?

Cheers!

**Comment by briis** [comment]
Do you get any errors in the Log file?

**Comment by Notrial** [comment]
Nothing related to the Smartweather component as far as I can see...let me inspect it further.

**Comment by briis** [comment]
I rechecked the code, if I get bad data from the API, I return a 0 value on all numeric sensors. 
There can be numerous reasons why we get bad data, especially when the are getting data from a source on the Internet.

Would it be possible for you to ignore all events with a 0 value in your chart?

**Comment by Notrial** [comment]
What you see as a flat line is actually correct readings btw... (small pressure differences)...but those 0 values mess up the graph range,

**Comment by Notrial** [comment]
hmm that makes sense. I'm using https://github.com/kalkih/mini-graph-card ....I'll look into it.

**Comment by dz4news** [comment]
I’m seeing the same issue with the pressure readings from my Tempest. I am using the historical graph template from within HA.

**Comment by briis** [comment]
II have released v2.2.2 that should fix this issue. It will simply not update the value, if it is 0, so it will just continue with the old value, until the next valid number is received. I have not had the chance to test this properly, as I have not gotten any fault data. So let me know if this solution fixes or do not fix the problem.
I will close this issue now, but feel free to re-open.
