### ISSUE TITLE
How to create a Tempest account

### ISSUE THREAD

**Issue by jeroenterheerdt** [briis/smartweather#54]
Not a real issue, but leaving it here for anyone that needs help. Since 2021 you need a Tempest account. To create a tempest account you need to install the tempest weatherflow app on your mobile phone.

**Comment by jeroenterheerdt** [comment]
After you have your account, go to https://tempestwx.com/ and sign-in. Go to Settings and choose Data Authorizations (almost at the bottom). Create a personal access token and use that as API key.

**Comment by briis** [comment]
I have added your tip to the README file. Will be in the next release. So I close this now.

**Comment by jeroenterheerdt** [comment]
thanks @briis . Although I was able to get an API key this way I was unable to use it, so it seems like we also need some of the oauth work from https://github.com/briis/pysmartweatherio/pull/14. But I'll let you to it. For now I have disable smartweather in my HA instance since it did not work.

**Comment by briis** [comment]
I don't understand. I and many other use this every day. Do you have your own station? Could you give me the Station ID?

**Comment by jeroenterheerdt** [comment]
I don't have my own station, I have been trying two stations in my neighborhood; 5393 and 20246. I also noticed that the station ID sometimes changes (which sounds weird to me)...https://tempestwx.com/map/20246/47.7311/-121.9569/15

**Comment by jeroenterheerdt** [comment]
for both I get "Invalid station ID or Station has no data". I copy pasted my API key that is on https://tempestwx.com/settings/tokens

**Comment by briis** [comment]
That is the Issue. The Api key you generate only works with a station registered to a station belonging to the same account. For now there is a public Token that works with any Public Station. I don't know for how long this will continue to work, but it works now and has been working for several years. Try this key: `20c70eae-e62f-4d3b-b3a4-8586e90f3ac8`

**Comment by jeroenterheerdt** [comment]
oh I thought that did not work any more and we should generate an API key for ourselves. Thanks.

**Comment by briis** [comment]
No it still works and I have not seen an end date posted. Hopefully an alternative will come when that happens.
