### ISSUE TITLE
Every station says no station ID or station has no data

### ISSUE THREAD

**Issue by mdegat01** [briis/smartweather#56]
I updated to 2.2.2 today and when I did it appears it created a whole new device marking all my existing ones as `unavailable`. To get rid of all these unusable entities at once I deleted the integration and then tried to re-add it. I used the exact same station id I was using before but now it won't work. In fact no station IDs around me seem to work, they all say "no station ID or station has no data". I tried rolling back to 2.2.1 and 2.1.0 and no change, no stations seem to work.

I tried deleting the `-`'s out of my access token just to see if those were only for UI display. When I did that I got an "invalid access token error". So I'm pretty confident my access token is valid, just for some reason I can't use any stations.

I tried turning on debug logging but nothing showed up so I'm pretty stumped. The station ID I want to use (and had been using without issue for months prior to this) is [39579](https://tempestwx.com/map/39579/42.3867/-71.012/12). Though like I said, I also tried most of the ones around as well without any success. 

If you have a known for sure working station I can try let me know and I'll try it. Also if there's any other way of getting debugging info on what is going on besides log level I can give that a shot as well.

**Comment by briis** [comment]
I just tried the above station id, and it works from here. As I believe I can read from your entry, you do not have your own station, and if that is the case you have to use this token (api key): `20c70eae-e62f-4d3b-b3a4-8586e90f3ac8`
This is the only Token that works for people who do not have a Station ID registeret on their Tempest Login.

If I do the combination of the above Token and Station ID 39579, then I get a Station in Vernon ST, with all the data.

**Comment by mdegat01** [comment]
That worked. What is that key then? Is that the developer key you mentioned in the component description that is supposed to have stopped working at the end of 2020? Or is that something I can use indefinitely? Basically trying to figure out if there a point in the relatively near future where I will have to buy their home weather kit to be able to continue using this component.

Btw I went through the readme and the linked guide on [how to obtain your own key](https://weatherflow.github.io/Tempest/api/oauth.html) and didn't see that key mentioned anywhere. Did it used to be somewhere that got remvoed?

**Comment by briis** [comment]
Yes the above key, is Public Developer key that has been around for a long time. Weatherflow announced that they would discontinue it, and they have removed it from their website. But it still works. I do not know for how long though.
There is talk about a new way of allowing people without a station, to access, but how is not completely clear to me at this point in time.

And the guide to obtain your own key, is only working if the user you register also has a station id registered to that same user. So I have a token/key for my station, but that key ONLY works for my station id. If I want to look at other stations, I use the ole developer key you got above.

So for now it works with that key. If and when I figure out how this will be substituted I will do my best to implement it in this Integration.

**Comment by mdegat01** [comment]
Ok sounds good. Thanks for the clarification, I'll keep an eye on it.

**Comment by michaelstein60** [comment]
I know this is a closed issue but I'm experiencing something very similar. Just purchased a Tempest and after setup I got a key and tried configuring the integration. I get the same error as above.

This is where it gets strange though. I tried the Public Developer key as instructed and entered my stationID 26436. The integration accepted this and presented me with someone else's data.

So, my developer key/stationID of the unit registered to me fails to configure, and the Public Key/stationID presents me with someone else's data.

Any suggestions on hoe to move forward from here?

**Comment by michaelstein60** [comment]
I found the problem. In the app (and web) interface each field has a number ST-00026436. When I dig into settings I find the public share is https://tempestwx.com/station/41305

I tried my key with ID 41305 and all worked! Perhaps the documentation could be more specific on where to find the ID?

**Comment by briis** [comment]
Yes the ST- number is the id of your Tempest device, and not your station id. I will look in to updating the documentation. Thanks
