### ISSUE TITLE
Version 2.2.2 all entities are unavailable

### ISSUE THREAD

**Issue by jeremyhamm** [briis/smartweather#57]
Since updating to 2.2.2 all of the existing entities are displayed as `unavailable`.

HACS - 1.10.1
Core   - 2021.1.5

Update Core to 2021.2.0 and all entities were unavailable

**Comment by briis** [comment]
Yes, I am sorry. I did not do my testing properly. If you go to the Integrations page, and select the SmartWeather Integration, you will most likely see that you now have at least two Entities defined: The old one and one called STATIONNAME_daily or STATIONNAME_hourly. The last one will contain your data.

So the fastest solution is to delete the Smartweather Integration and re-add it. The Entity created will now be called _daily or _hourly based on the Forecast Interval you selected. You will then have to change that name in Lovelace or rename the Weather Entity to what is was before.

**Comment by jeremyhamm** [comment]
That fixed it! Thanks for all of your hard with, this is my favorite HA integration.

**Comment by dz4news** [comment]
Agree. This is a great integration, thank you for all your work.

**Comment by jeremyhamm** [comment]
@briis Do you have a Github sponsors link?  I would like to support this project.

**Comment by briis** [comment]
I am glad you got it back and sorry for the inconvenience this has caused. 
@jeremyhamm You don't have to sponsor me for doing this. I get so much from the Home Assistant community, so I am just glad that I can also contribute a little. But thanks for asking.
