### ISSUE TITLE
Smartweather stopped working

### ISSUE THREAD

**Issue by michaelstein60** [briis/smartweather#62]
I've been running the latest stable HACS version (currently 2.2.2) for the last month and it's been stable. In the middle os last night I got a notification from my tempest app that the station was unreachable, but when tested this morning all was OK.

HA however shows all sensors as unreachable.

I uninstalled the add-on and HACS and started fresh. I even generated a new token.

On fresh install the Device is created and reports version 1.47, but no entities are created.

I've tried a couple of times to reinstall. I'm also not seeing any errors or warnings

- [ ] 2021-03-04 07:46:34 INFO (MainThread) [homeassistant.setup] Setting up smartweather
- [ ] 2021-03-04 07:46:34 INFO (MainThread) [homeassistant.setup] Setup of domain smartweather took 0.0 seconds
- [ ] 2021-03-04 07:46:35 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.smartweather
- [ ] 2021-03-04 07:46:35 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.smartweather
- [ ] 2021-03-04 07:46:35 INFO (MainThread) [homeassistant.components.weather] Setting up weather.smartweather

**Comment by michaelstein60** [comment]
Just solved the problem myself. Sorry for the false report.

Turns out the weather station decided it was no longer in range of the hub. I didn't notice since the status shows OnLine (in tempest app) which turns out to be the online status of the Hub and not the station. Need to dig deeper for the station status. 

Thanks for a great integration!

**Comment by briis** [comment]
Glad you solved it. And I have had this report a few times, as you state, the App says online - which is true, but device is not online. I get a notification on my phone when that happens, btw.
