### ISSUE TITLE
Public API down or not working

### ISSUE THREAD

**Issue by w1tw0lf** [briis/smartweather#64]
Seems like the public API, 20c70eae-e62f-4d3b-b3a4-8586e90f3ac8 has stopped working.

Had no data displayed this morning. Removed and re-added the integration but only getting one device with no entities create

**Comment by briis** [comment]
Just tested it with my own station, and it works fine here. What station id are you using?

**Comment by w1tw0lf** [comment]
Using 15614 which was working 100s before.

**Comment by w1tw0lf** [comment]
Seems like the station went offline. No worries.

**Comment by briis** [comment]
I just checked what is coming from that station, and it seems not to be reporting data right now. You can check it your self on the Tempest API Explorer, by using the key to Authorize and then enter your station id.

https://weatherflow.github.io/Tempest/api/swagger/#!/observations/getStationObservation

So there is nothing wrong with the Integration, it simply does not get any data.

**Comment by briis** [comment]
> Seems like the station went offline. No worries.
I was writing my comment, while you posted this. But we agree. 👍🏼

**Comment by w1tw0lf** [comment]
Trying to figure out how to get one off these stations for my self in South Africa but not finding any way how to. At least this one is about 10km away from me :)

Thanks for awesome integration. May close this one.

**Comment by briis** [comment]
I was one of the initial backers in Kickstarter, so I have the old version, that consist of two units AIR and SKY. But these are gone out of production, so now they only sell the new Integrated TEMPEST units - but unfortunately they only ship to the US, and have been for a while. Maybe if you have a friend in the US you can get one shipped there?

**Comment by w1tw0lf** [comment]
Have few work related friends in Canada. Waiting to hear when they allowed/planning to visit. Will order one then and have it shipped to them.

**Comment by briis** [comment]
Yes, Corona sucks. Have a great day.

**Comment by w1tw0lf** [comment]
Yup, sucks big time. Same for you.
