### ISSUE TITLE
Wind Average - Request

### ISSUE THREAD

**Issue by lanky8804** [briis/smartweather#66]
More of a feature request but is it possible to have an average wind speed sensor added?

**Comment by briis** [comment]
Hi,
Weatherflow reports two wind speeds: Average Wind Speed and Wind Gust
The sensor `sensor.smartweather_wind_speed` is showing the Average Wind Speed, so you already have it. If you want more realtime wind speed use `sensor.smartweather_wind_gust`

I realize I could have named it better, so sorry for the confusion.

**Comment by lanky8804** [comment]
Ah ok, When you view the data on the tempest website you have a Gust, average and a Lull. Makes sense now.

Thank you

**Comment by briis** [comment]
I have not added the Lull value - I never figured when it would be useful.
