### ISSUE TITLE
Temp_high/low_today wrong units?

### ISSUE THREAD

**Issue by chasut** [briis/smartweather#70]
Seeing another anomaly.  For the weather entity, the temp_high_today and temp_low_today attributes appear to be in Celsius even though all other temperatures are in Fahrenheit.

Double thank you for creating/maintaining this and responding so quickly.  Can't imagine how you made this so good without having access to the hardware!

Best

**Comment by briis** [comment]
Thanks. And I do have some HW, just not the Tempest Unit, as this is not available in Europe. 
I was one of the initial backers and received the older devices, which is split in two, so you have an AIR device and a SKY device. All this is now merged in to the Tempest unit. That means I have some local data I can test on, and then I have to rely on WeatherFlow to keep the API docs updated for 😬

Anyway, I will fix the High/Low temp ASAP

**Comment by briis** [comment]
Closed with the 2.2.8 release
