### ISSUE TITLE
Please add Oauth2 support

### ISSUE THREAD

**Issue by shidarin** [briis/smartweather#71]
As official support for the public API key winds down, can the smartweather integration get Oauth2 support? Of course an additional question might be- would oauth2 support have access to public weatherstation data? If not, there's probably no point to this ticket. If you already have your own weatherflow station, you have the ability to get a personal api key already.

The public API key which was posted on [this](https://weatherflow.github.io/SmartWeather/api/) page has been removed and the the page now redirects to Oauth2 instructions

The API key [was supposed to be disabled at the end of 2020](https://community.weatherflow.com/t/update-to-api-documentation/9989). It still works as of today, but we don't know for how much longer.

**Comment by briis** [comment]
Hi,
I still need to get that statement from WeatherFlow that oauth2 support will give access to public weatherstations - I have not found it yet. I do assume this is the purpose, as the Personal Token for when you own a Station Works fine, and is easy to use.

So I will leave this open, and then decide next steps when I know the use case for oauth2.

**Comment by briis** [comment]
Did a little digging, and found the below statement in the [*Tempest API Remote Data Access Policy*](https://weatherflow.github.io/Tempest/api/remote-developer-policy.html). Especially the last sentence seems to indicate that it will no longer be possible to get public data, unless you want to do something on a commercial level with WeatherFlow - which I will not do. So I don't believe implementing oauth2, will make any difference. 

"All data (observations, forecast & metadata) is available to station owners from stations that they own (public or private) via any application. No data (observations, forecast or metadata) is available from private stations via any application. Metadata from public stations is available to any user via any application. **Observation and forecast data from public stations may be available to any user via licensed enterprise applications (please contact us for details).**"

**Comment by briis** [comment]
I now read the data access policy a few times, and it is clear that no matter what authentication method you use, there will be no access to stations you don't own, for non commercial applications. So I will not spend time on adding this, as the personal token works fine, and adding oauth2 will not make any difference.

**Comment by shidarin** [comment]
Understood Briis, thanks for looking into it. I'll write them a letter hoping they can be persuaded. Personal API keys should at least have access to other public station data.
