### ISSUE TITLE
Lightning Sensors

### ISSUE THREAD

**Issue by chasut** [briis/smartweather#73]
With thunderstorms today, I have been playing with the lightning information and have some observations.  There is at least one anomaly on the WeatherFlow side that I sent a support request to get some additional information.  The others, may or may not be issues, I just may not understand how they are intended to work.  Anyway, observations/comments on sensors:

lighning_count - The state remained 0, even though lightning was detected and the 3hr value was > 0.  Perhaps this is instantaneous and mirrors the binary_sensor?  wasn't able to see both at the same time.

lightning_last_1hrs - I swear I saw this >0 during the first wave of storms, but stayed at zero during the second wave.  Perhaps it is related to the WeatherFlow issue with last detected below?

lightning_last_3hrs - Working as expected and consistent with Tempest web app

lightning_time - Strange anomaly from WeatherFlow information.  Their summary would accurately show the relative time (e.g. 3 minutes), but the Last Detected lightning in the details would be much earlier (e.g. 2 hours) like it was showing a prior event.  The distance was similarly as if it was from  a prior event.  Very odd, but the sensor matches what is displayed in the Tempest web app.

Not sure what my ask is, but wanted to report in case it is helpful.  Thanks again.

**Comment by chasut** [comment]
Ok, next storm cell with different results; maybe I am crazy.  This time the WeatherFlow app was consistent between the summary and details, so probably why the integration behaved differently.  So, this could all be on the WeatherFlow side.

lightning count - State was 1, on the last lightning
lightning_last 1hrs - also moved to >0 on this storm; not sure what the difference was this time

**Comment by briis** [comment]
Lightning detection is and has always been a bit shaky and not too reliable, that is at least my experience.
I just pull the data that is in the system, so I suggest you go to the weatherflow forum, to see what others are wiring about this, and to fully understand when a specific value is filled out.

**Comment by chasut** [comment]
Interestingly enough, the lightning detection improved dramatically in just these 48hours.  We have had several storms pass so I have been monitoring.  Perhaps it took a bit of learning for the AI engine on the WF side.  Also, I modified the integration to allow a more frequent refresh (currently set to 20s) just to see what would happen and if it would break something.   I believe the lightning_count sensor is strikes in the last minute (like the description in the UDP version).  With the faster refresh rate it has been quick and reliable.  I generally see the updates well before the app/website, although a bit after the iOS notification.

Good suggestion on the WF forum.  When it is stormy and I have nothing better to do than futz with my new weather kit ;)

As regards the integration, I think it is working great, and as expected for the lightning sensors, so feel free to close this issue.  And thank you for indulging me.

**Comment by briis** [comment]
So happy that it has improved. I guess it is just us guys with old HW, where it is still unreliable. I get lightning detection daily even on a clear sunny day 😁

Please keep suggestions coming, it is a good way of improving the integration. You found two errors nobody else had seen for 12 month.

I will close. Thanks
