### ISSUE TITLE
Token ID

### ISSUE THREAD

**Issue by ciairmi** [briis/smartweather#85]
Hi, I've already configured 3 different station into HA as integrations.
Now I'd like to add a new station but I'm not able to recover the token from the https://tempestwx.com/signin.html, because I don't remember the email account I've used.
Is there any way to recover the Token from the codes into the integrations?
Thanks
Bye

**Comment by briis** [comment]
Yes there is:

You need to get access to the root of the file system of your Home Assistant installation. (That is where you find `configuration.yaml` and all the other files.

When here enter the directory `.storage`. Note the . in front of the file, which means it is a hidden directory.
Then open the file `core.config_entries`. In this file search for `smartweather` and just below where it finds that string, you can see your token after the field `api_key`.

Hope you can figure it out.

**Comment by ciairmi** [comment]
Did it, thank you so much.
Bye

**Comment by briis** [comment]
I close the issue.
