### ISSUE TITLE
integration not listed

### ISSUE THREAD

**Issue by joseftsch** [briis/smartweather#86]
Hey, 

I installed this integration successfully via HACS. 
I can see the folder /config/custom_components/smartweather in the filesystem and the content seems fine as well.

Despite having restarted HA several times I am unable to add this integration via Configuration-Integration as it is not listed.

Using HA: Home Assistant 2021.11.5
HACS: 1.18.0

Is there any known issue?

**Comment by briis** [comment]
No. I do believe this is a caching issue with your browser. While on the Integrations page in HA, do a hard refresh of your browser, and try again.

**Comment by joseftsch** [comment]
Yeah, that worked ... Thank you! :)
Sorry for having wasted your time ...

**Comment by briis** [comment]
No worries.

**Comment by briis** [comment]
Hi Josef,
FYI, this Integration will soon have End of Life, as it is being replaced with a more updated and modern version called [WeatherFlow Weather](https://github.com/briis/hass-weatherflow/blob/main/README.md). So before you spend a lot of time settings these sensors up in the UI, I would recommend that you de-install `smartweather` again, and then follow the link above to install the new Integration. They can co-exist, but it does not make sense to have them both.

The only reason it is not officially announced yet, is that I am waiting for it be part of the Default HACS store. The submission is done, and waiting for the next update. Until then you can install it from HACS using the instructions in the link above.

**Comment by joseftsch** [comment]
Hey,
Cool! Thanks for letting me know :)
